// Generated from src/sdk_artifacts.zig. Do not edit by hand.
import Foundation

public let controlProtocol = "unified-v2"
public let acheronRuntimeVersion = "acheron-1"
public let nodeFsProtocol = "unified-v2-fs"
public let nodeFsProto: UInt32 = 2

public let controlMessageTypes: [String] = [
    "control.version",
    "control.version_ack",
    "control.connect",
    "control.connect_ack",
    "control.session_attach",
    "control.session_status",
    "control.session_resume",
    "control.session_list",
    "control.session_close",
    "control.session_restore",
    "control.session_history",
    "control.ping",
    "control.pong",
    "control.metrics",
    "control.auth_status",
    "control.auth_rotate",
    "control.node_invite_create",
    "control.node_join_request",
    "control.node_join_pending_list",
    "control.node_join_approve",
    "control.node_join_deny",
    "control.node_join",
    "control.node_ensure",
    "control.node_lease_refresh",
    "control.venom_bind",
    "control.venom_upsert",
    "control.venom_get",
    "control.agent_ensure",
    "control.agent_list",
    "control.agent_get",
    "control.node_list",
    "control.node_get",
    "control.node_delete",
    "control.workspace_create",
    "control.workspace_update",
    "control.workspace_delete",
    "control.workspace_list",
    "control.workspace_get",
    "control.workspace_template_list",
    "control.workspace_template_get",
    "control.workspace_mount_set",
    "control.workspace_mount_remove",
    "control.workspace_mount_list",
    "control.workspace_bind_set",
    "control.workspace_bind_remove",
    "control.workspace_bind_list",
    "control.workspace_token_rotate",
    "control.workspace_token_revoke",
    "control.workspace_activate",
    "control.workspace_up",
    "control.project_create",
    "control.project_update",
    "control.project_delete",
    "control.project_list",
    "control.project_get",
    "control.project_mount_set",
    "control.project_mount_remove",
    "control.project_mount_list",
    "control.project_token_rotate",
    "control.project_token_revoke",
    "control.project_activate",
    "control.workspace_status",
    "control.reconcile_status",
    "control.project_up",
    "control.audit_tail",
    "control.error",
]

public let acheronMessageTypes: [String] = [
    "acheron.t_version",
    "acheron.r_version",
    "acheron.t_attach",
    "acheron.r_attach",
    "acheron.t_walk",
    "acheron.r_walk",
    "acheron.t_open",
    "acheron.r_open",
    "acheron.t_read",
    "acheron.r_read",
    "acheron.t_write",
    "acheron.r_write",
    "acheron.t_stat",
    "acheron.r_stat",
    "acheron.t_clunk",
    "acheron.r_clunk",
    "acheron.t_flush",
    "acheron.r_flush",
    "acheron.t_fs_hello",
    "acheron.r_fs_hello",
    "acheron.t_fs_exports",
    "acheron.r_fs_exports",
    "acheron.t_fs_lookup",
    "acheron.r_fs_lookup",
    "acheron.t_fs_getattr",
    "acheron.r_fs_getattr",
    "acheron.t_fs_readdirp",
    "acheron.r_fs_readdirp",
    "acheron.t_fs_symlink",
    "acheron.r_fs_symlink",
    "acheron.t_fs_setxattr",
    "acheron.r_fs_setxattr",
    "acheron.t_fs_getxattr",
    "acheron.r_fs_getxattr",
    "acheron.t_fs_listxattr",
    "acheron.r_fs_listxattr",
    "acheron.t_fs_removexattr",
    "acheron.r_fs_removexattr",
    "acheron.t_fs_open",
    "acheron.r_fs_open",
    "acheron.t_fs_read",
    "acheron.r_fs_read",
    "acheron.t_fs_close",
    "acheron.r_fs_close",
    "acheron.t_fs_lock",
    "acheron.r_fs_lock",
    "acheron.t_fs_create",
    "acheron.r_fs_create",
    "acheron.t_fs_write",
    "acheron.r_fs_write",
    "acheron.t_fs_truncate",
    "acheron.r_fs_truncate",
    "acheron.t_fs_unlink",
    "acheron.r_fs_unlink",
    "acheron.t_fs_mkdir",
    "acheron.r_fs_mkdir",
    "acheron.t_fs_rmdir",
    "acheron.r_fs_rmdir",
    "acheron.t_fs_rename",
    "acheron.r_fs_rename",
    "acheron.t_fs_statfs",
    "acheron.r_fs_statfs",
    "acheron.e_fs_inval",
    "acheron.e_fs_inval_dir",
    "acheron.err_fs",
    "acheron.error",
]

public let runtimeAcheronMessageTypes: [String] = [
    "acheron.t_version",
    "acheron.r_version",
    "acheron.t_attach",
    "acheron.r_attach",
    "acheron.t_walk",
    "acheron.r_walk",
    "acheron.t_open",
    "acheron.r_open",
    "acheron.t_read",
    "acheron.r_read",
    "acheron.t_write",
    "acheron.r_write",
    "acheron.t_stat",
    "acheron.r_stat",
    "acheron.t_clunk",
    "acheron.r_clunk",
    "acheron.t_flush",
    "acheron.r_flush",
    "acheron.error",
]

public let nodeFsAcheronMessageTypes: [String] = [
    "acheron.t_fs_hello",
    "acheron.r_fs_hello",
    "acheron.t_fs_exports",
    "acheron.r_fs_exports",
    "acheron.t_fs_lookup",
    "acheron.r_fs_lookup",
    "acheron.t_fs_getattr",
    "acheron.r_fs_getattr",
    "acheron.t_fs_readdirp",
    "acheron.r_fs_readdirp",
    "acheron.t_fs_symlink",
    "acheron.r_fs_symlink",
    "acheron.t_fs_setxattr",
    "acheron.r_fs_setxattr",
    "acheron.t_fs_getxattr",
    "acheron.r_fs_getxattr",
    "acheron.t_fs_listxattr",
    "acheron.r_fs_listxattr",
    "acheron.t_fs_removexattr",
    "acheron.r_fs_removexattr",
    "acheron.t_fs_open",
    "acheron.r_fs_open",
    "acheron.t_fs_read",
    "acheron.r_fs_read",
    "acheron.t_fs_close",
    "acheron.r_fs_close",
    "acheron.t_fs_lock",
    "acheron.r_fs_lock",
    "acheron.t_fs_create",
    "acheron.r_fs_create",
    "acheron.t_fs_write",
    "acheron.r_fs_write",
    "acheron.t_fs_truncate",
    "acheron.r_fs_truncate",
    "acheron.t_fs_unlink",
    "acheron.r_fs_unlink",
    "acheron.t_fs_mkdir",
    "acheron.r_fs_mkdir",
    "acheron.t_fs_rmdir",
    "acheron.r_fs_rmdir",
    "acheron.t_fs_rename",
    "acheron.r_fs_rename",
    "acheron.t_fs_statfs",
    "acheron.r_fs_statfs",
    "acheron.e_fs_inval",
    "acheron.e_fs_inval_dir",
    "acheron.err_fs",
]

public let legacyRejectedControlMessageTypes: [String] = [
    "session.send",
    "control.debug_subscribe",
    "control.debug_unsubscribe",
    "control.node_service_watch",
    "control.node_service_unwatch",
    "control.node_service_event",
    "control.venom_watch",
    "control.venom_unwatch",
    "control.venom_event",
]

public let legacyRejectedAcheronMessageTypes: [String] = [
    "acheron.t_hello",
    "acheron.fs_t_*",
    "acheron.fs_r_*",
    "acheron.fs_evt_*",
    "acheron.fs_error",
]

public enum Channel: String, CaseIterable, Sendable {
    case control
    case acheron
}

public enum ProtocolEnvelopeRule: String, CaseIterable, Sendable {
    case channelRequired = "channel-required"
    case typeMustMatchChannel = "type-must-match-channel"
    case legacyNamesRejected = "legacy-names-rejected"
    case correlationByIdOrTag = "correlation-by-id-or-tag"
}

public let protocolEnvelopeRules: [ProtocolEnvelopeRule] = [
    .channelRequired,
    .typeMustMatchChannel,
    .legacyNamesRejected,
    .correlationByIdOrTag,
]
